#' Data Input (Targeted)
#'
#' Reads input data from exported Skyline raw files.
#'
#' @param dir1 Load all files from the specified directory if not NULL.
#' @return List containing formatted input data and metadata
#' for downstream analysis.
#' @examples
#'
#' # msT_input(
#' #   dir1 = "data/"
#' # )
#'
#' @export
msT_input <- function( # nolint
  dir1 = NULL
) {
  # Load data
  f1 <- list.files(dir1, full.names = TRUE)
  f2 <- f1[grepl("sample", f1) & grepl(".txt", f1)]
  f3 <- f1[grepl("order", f1) & grepl(".txt", f1)]
  f1 <- f1[f1 %in% f2 == FALSE]
  f1 <- f1[f1 %in% f3 == FALSE]
  d1 <- setNames(
    lapply(
      f1,
      function(x) {
        if(grepl(".tsv", x)) { # nolint
          d1a <- read.table(x, sep = "\t", header = TRUE)
        }
        if(grepl(".csv", x)) { # nolint
          d1a <- read.csv(x)
        }
        dref <- gsub(paste(dir1, "/", sep = ""), "", x)
        return(list("data" = d1a, "file" = dref)) # nolint
      }
    ),
    gsub("\\.tsv|\\.csv", "", gsub(paste(dir1, "/", sep = ""), "", f1))
  )
  # Load sample list (if present)
  if(length(f2) == 1) { # nolint
    print("Sample list found in directory; loading sample list along with data")
    d1b <- read.table(f2, sep = "\t", header = TRUE)
  }
  if(length(f3) == 1) { # nolint
    print("Injection order found in directory; loading order along with data")
    d1c <- read.table(f3, sep = "\t", header = TRUE)
  }
  if(exists("d1b") && !exists("d1c")) { # nolint
    ld <- list("data" = d1, "sample_list" = d1b)
  }
  if(!exists("d1b") && exists("d1c")) { # nolint
    ld <- list("data" = d1, "sample_order" = d1c)
  }
  if(exists("d1b") && exists("d1c")) { # nolint
    ld <- list("data" = d1, "sample_list" = d1b, "sample_order" = d1c)
  }
  if(!exists("d1b") && !exists("d1c")) { # nolint
    ld <- list("data" = d1)
  }
  return(ld) # nolint
}

#' Data Format (Targeted)
#'
#' Formats input data from exported Skyline raw files. Must have
#' imported a valid sample list containing group information and from
#' msT_input and the exported sample_order if processing Skyline-based
#' targeted data.
#'
#' @param dat Data object generated by msT_input function.
#' @return List containing formatted input data and metadata
#' for downstream analysis.
#' @examples
#'
#' # msT_format(
#' #   dat = d1
#' # )
#'
#' @import dplyr
#' @export
msT_format <- function( # nolint
  dat,
  intype = "Skyline"
) {
  # Load data and consolidate chromatogram and peak intensities
  ld1 <- dat
  ## If input type is Skyline (default)
  if(intype == "Skyline") { # nolint
    # Format chromatogram data
    ld1[["data"]][["chromatograms"]][[1]] <- setNames(ld1[["data"]][["chromatograms"]][[1]][ # nolint
      , c(
        "PeptideModifiedSequence", "PrecursorCharge", "ProductMz",
        "TotalArea", "Times", "Intensities"
      )
    ], c(
      "Name", "Adduct", "Product(mz)",
      "Peak_area_total", "RT_all", "Intensity"
    ))
    ## Important: Skyline exports intensities and chromatograms differently!
    ## Need column indicating sample order in Skyline and count of unique
    ## compounds exported from software.
    # Format intensities
    ld1[["data"]][["intensities"]][[1]] <- setNames(ld1[["data"]][["intensities"]][[1]][ # nolint
      , c(
        "Molecule", "Molecule.List.Name", "Replicate.Name",
        "Precursor.Mz", "Retention.Time", "Area", "Background"
      )
    ], c(
      "Name", "synthesis_pathway", "SampleID",
      "Precursor(mz)", "RT", "Peak_area", "Background"
    ))
    # Format transition list
    ld1[["data"]][["transition_list"]][[1]] <- setNames(ld1[["data"]][["transition_list"]][[1]][ # nolint
      , c(
        "Molecule.List.Name", "Molecule.Name", "Molecule.Formula",
        "Precursor.Mz", "Product.Mz"
      )
    ], c(
      "synthesis_pathway", "Name", "Formula",
      "Precursor(mz)", "Product(mz)"
    ))
    # Merge chromatograms with intensities
    ## Set order of chromatograms to match intensities
    ## Assign chromatogram sample identities
    ld1[["data"]][["chromatograms"]][[1]] <- dplyr::select(
      dplyr::mutate(
        ld1[["data"]][["chromatograms"]][[1]],
        "SampleID" = unlist(
          lapply(
            as.numeric(ld1[["sample_order"]][["Order"]]),
            function(x) {
              rep(
                ld1[["sample_order"]][["SampleID"]][[x]],
                length(
                  unique(
                    ld1[["data"]][["chromatograms"]][[1]][["Name"]]
                  )
                )
              )
            }
          )
        )
      ),
      "SampleID", everything() # nolint
    )
    ld1[["data"]][["merged"]] <- dplyr::left_join(
      ld1[["data"]][["intensities"]][[1]],
      ld1[["data"]][["chromatograms"]][[1]],
      by = c("SampleID", "Name")
    )
    ld1[["data"]][["merged"]] <- dplyr::select(
      dplyr::left_join(
        ld1[["data"]][["merged"]],
        ld1[["data"]][["transition_list"]][[1]][
          , c("Name", "Formula")
        ],
        by = "Name"
      ), "Name", "Formula", "SampleID", everything() # nolint
    )
    # Create index and assign groups
    ld1[["data"]][["merged"]][["ID"]] <- seq.int(
      1,
      nrow(ld1[["data"]][["merged"]]),
      1
    )
    ld1[["data"]][["merged"]][["Sample"]] <- gsub(
      "_.*", "", ld1[["data"]][["merged"]][["SampleID"]]
    )
    ld1[["sample_list"]][["SampleID"]] <-
      ld1[["sample_list"]][["WCMC_Sample_ID"]]
    ld1[["sample_list"]][["Group"]] <- ld1[["sample_list"]][["sub_treatment"]]
    ld1[["sample_list"]][["Type"]] <- ld1[["sample_list"]][["treatment"]]
    ld1[["sample_list"]][["Sample"]] <- gsub(
      "_.*", "", ld1[["sample_list"]][["SampleID"]]
    )
    ld1[["data"]][["merged"]] <- dplyr::select(
      dplyr::left_join(
        ld1[["data"]][["merged"]],
        ld1[["sample_list"]][
          ,
          c("Sample", "Code", "Replicate","Type", "Group")
        ],
        by = "Sample"
      ),
      "ID", "Sample", "Code", "Replicate","Type", "Group", everything() # nolint
    )
    ## Assign quality control types
    ld1[["data"]][["merged"]][["Replicate"]] <- ifelse(
      is.na(ld1[["data"]][["merged"]][["Replicate"]]),
      1,
      ld1[["data"]][["merged"]][["Replicate"]]
    )
    ld1[["data"]][["merged"]][["Code"]] <- ifelse(
      is.na(ld1[["data"]][["merged"]][["Code"]]),
      1,
      ld1[["data"]][["merged"]][["Code"]]
    )
    ld1[["data"]][["merged"]][["Group"]] <- ifelse(
      is.na(ld1[["data"]][["merged"]][["Group"]]) &
        grepl("QC|qc", ld1[["data"]][["merged"]][["SampleID"]]),
      "QC",
      ifelse(
        is.na(ld1[["data"]][["merged"]][["Group"]]) &
          grepl("MB|mb", ld1[["data"]][["merged"]][["SampleID"]]),
        "Blank",
        ifelse(
          is.na(ld1[["data"]][["merged"]][["Group"]]) &
            grepl("cal", ld1[["data"]][["merged"]][["SampleID"]]),
          "Std_curve",
          ifelse(
            is.na(ld1[["data"]][["merged"]][["Group"]]) &
              grepl("Pool|pool", ld1[["data"]][["merged"]][["SampleID"]]),
            "Pool",
            ifelse(
              is.na(ld1[["data"]][["merged"]][["Group"]]) &
                grepl("preinj", ld1[["data"]][["merged"]][["SampleID"]]),
              "Preinjection",
              ld1[["data"]][["merged"]][["Group"]]
            )
          )
        )
      )
    )
    ## Assign sample type
    ld1[["data"]][["merged"]][["Type"]] <- ifelse(
      grepl(
        "QC|Blank|Std_curve|Pool|Preinjection",
        ld1[["data"]][["merged"]][["Group"]]
      ),
      "QC",
      ld1[["data"]][["merged"]][["Type"]]
    )
    ## Rename experimental samples to match code, replicate, and group names
    ## EDIT to allow flexible column input
    ld1[["data"]][["merged"]][["label"]] <- ifelse(
      grepl(
        "QC|Blank|Std_curve|Pool|Preinjection",
        ld1[["data"]][["merged"]][["Group"]]
      ),
      ld1[["data"]][["merged"]][["SampleID"]],
      paste(
        ld1[["data"]][["merged"]][["Code"]],
        ld1[["data"]][["merged"]][["Replicate"]],
        sep = "."
      )
    )
    ## Assign injection order (if present)
    ld1[["data"]][["merged"]] <- dplyr::select(
      dplyr::left_join(
        ld1[["data"]][["merged"]],
        ld1[["sample_order"]],
        by = "SampleID"
      ),
      "Order", "label", everything() # nolint
    )
  }
  return(ld1[["data"]][["merged"]])
}
