#' Data Normalization
#'
#' Includes multiple methods for data normalization. Currently supported methods
#' are internal standard. Planned methods include total ion count (TIC), LOESS,
#' and SERRF.
#'
#' @param ld1 A SummarizedExperiment object, usually generated by ms_postproc.
#' @param mtd Normalization method (either "tic", "iSTD", or "LOESS").
#' @return A SummarizedExperiment containing normalized
#' compound intensities and metadata.
#' @examples
#'
#' # data1 <- ms_data_norm(ld1 = data1)
#'
#' @import SummarizedExperiment
#' @import parallel
#' @import dplyr
#' @export
ms_data_norm <- function( # nolint
  ld1,
  mtd = "iSTD"
) {
  print("1. Loading SummarizedExperiment")
  # Load SummarizedExperiment
  dnorm <- ld1
  #---- Internal standard normalization ----
  if(mtd == "iSTD") { # nolint
    print("2. Checking metadata")
    # Check metadata information prior to normalization
    print("Selected method is iSTD; checking for necessary metadata information in input object...") # nolint
    if (
      c("Internal standard prefix") %in%
        names(metadata(dnorm)) == FALSE # nolint
    ) {
      print("Must include 'Internal standard prefix' in metadata if performing internal standard normalization!") # nolint
    }
    print("3. Performing iSTD normalization")
    if (Sys.info()[["sysname"]] != "Windows") {
      core_num <- ceiling(parallel::detectCores() / 4)
      # Check for imputed assay in object
      if (
        "imputed" %in%
          names(SummarizedExperiment::assays(dnorm)) == FALSE
      ) {
        print("Imputing NAs and zeroes with 1/10th of the minimum peak height for each compound...") # nolint
        SummarizedExperiment::assay(
          dnorm, "imputed", withDimnames = FALSE
        ) <-
          as.matrix(
            dplyr::bind_rows(
              parallel::mclapply(
                mc.cores = core_num,
                seq.int(1, nrow(dnorm), 1),
                function(x) {
                  d1 <- SummarizedExperiment::assay(dnorm, "raw")[x, ]
                  d1[is.na(d1)] <- 0
                  d1 <- ifelse(
                    d1 == 0,
                    round(
                      0.1 * min(d1[
                        d1 > 0
                      ]), digits = 0
                    ),
                    d1
                  )
                  d1 <- as.data.frame(t(d1))
                  return(d1) # nolint
                }
              )
            )
          )
      }
      # Normalize to iSTD average
      ## Calculate iTIC sums average by subsetting imputed assay
      ## and split if both ionization modes are present
      ### iSTD sum per mode
      istd_sum <- setNames(as.data.frame(
        lapply(
          metadata(dnorm)[["Ionization mode"]], # nolint
          function(i) {
            colSums(assay(dnorm, "imputed")[ # nolint
              grepl(metadata(dnorm)[["Internal standard prefix"]], rowData(dnorm)[["Label"]]) & # nolint
                grepl(i, rowData(dnorm)[["Mode"]]), # nolint
            ])
          }
        )
      ), metadata(dnorm)[["Ionization mode"]])
      ### iSTD average sum per mode
      if ("Batch column name" %in% names(metadata(dnorm))) { # nolint
        print("Batch column name detected in object metadata; splitting iSTD calculation by batch...") # nolint
        istd_avg <- setNames(as.data.frame(
          lapply(
            names(istd_sum), # nolint
            function(a) {
              unlist(
                lapply(
                  colData(dnorm)[[metadata(dnorm)[["Batch column name"]]]], # nolint
                  function(j) {
                    mean(istd_sum[[a]][
                      grepl(
                        j,
                        colData(dnorm)[[metadata(dnorm)[["Batch column name"]]]] # nolint
                      )
                    ])
                  }
                )
              )
            }
          )
        ), names(istd_sum))
      }
      if ("Batch column name" %in% names(metadata(dnorm)) == FALSE) { # nolint
        istd_avg <- unlist(lapply(names(istd_sum), function(x) mean(x)))
      }
      ## Normalize each compound to iSTD average
      SummarizedExperiment::assay(
        dnorm, "norm", withDimnames = FALSE
      ) <- as.matrix(
        dplyr::bind_rows(
          parallel::mclapply(
            mc.cores = core_num,
            seq.int(1, nrow(dnorm), 1),
            function(x) {
              # Select row
              d1 <- SummarizedExperiment::assay(dnorm, "imputed")[x, ]
              # Calculate normalized peak heights
              ## toggle between ionization modes
              d1 <- (
                # raw peak height
                d1 /
                  # internal standard sum for mode
                  istd_sum[[rowData(dnorm)[["Mode"]][[x]]]] # nolint
              ) *
                # internal standard average sum for mode
                istd_avg[[rowData(dnorm)[["Mode"]][[x]]]]
              return(d1) # nolint
            }
          )
        )
      )
      # Add raw/imputed/norm TIC columns to column metadata
      colData(dnorm) <- cbind( # nolint
        colData(dnorm), # nolint
        dplyr::bind_cols(
          lapply(
            metadata(dnorm)[["Ionization mode"]], # nolint
            function(i) {
              setNames(as.data.frame(lapply(
                names(assays(dnorm)), # nolint
                function(j) {
                  colSums(assay(dnorm, j)[ # nolint
                    grepl(i, rowData(dnorm)[["Mode"]]), # nolint
                  ])
                }
              )), paste("TIC", i, names(assays(dnorm)), sep = ".")) # nolint
            }
          )
        )
      )
    }
    if (Sys.info()[["sysname"]] == "Windows") {
      # Check for imputed assay in object
      if (
        "imputed" %in%
          names(SummarizedExperiment::assays(dnorm)) == FALSE
      ) {
        print("Imputing NAs and zeroes with 1/10th of the minimum peak height for each compound...") # nolint
        SummarizedExperiment::assay(
          dnorm, "imputed", withDimnames = FALSE
        ) <-
          as.matrix(
            dplyr::bind_rows(
              lapply(
                seq.int(1, nrow(dnorm), 1),
                function(x) {
                  d1 <- SummarizedExperiment::assay(dnorm, "raw")[x, ]
                  d1[is.na(d1)] <- 0
                  d1 <- ifelse(
                    d1 == 0,
                    round(
                      0.1 * min(d1[
                        d1 > 0
                      ]), digits = 0
                    ),
                    d1
                  )
                  d1 <- as.data.frame(t(d1))
                  return(d1) # nolint
                }
              )
            )
          )
      }
      # Normalize to iSTD average
      ## Calculate iTIC sums average by subsetting imputed assay
      ## and split if both ionization modes are present
      ### iSTD sum per mode
      istd_sum <- setNames(as.data.frame(
        lapply(
          metadata(dnorm)[["Ionization mode"]], # nolint
          function(i) {
            colSums(assay(dnorm, "imputed")[ # nolint
              grepl(metadata(dnorm)[["Internal standard prefix"]], rowData(dnorm)[["Label"]]) & # nolint
                grepl(i, rowData(dnorm)[["Mode"]]), # nolint
            ])
          }
        )
      ), metadata(dnorm)[["Ionization mode"]])
      ### iSTD average sum per mode
      if ("Batch column name" %in% names(metadata(dnorm))) { # nolint
        print("Batch column name detected in object metadata; splitting iSTD calculation by batch...") # nolint
        istd_avg <- setNames(as.data.frame(
          lapply(
            names(istd_sum), # nolint
            function(a) {
              unlist(
                lapply(
                  colData(dnorm)[[metadata(dnorm)[["Batch column name"]]]], # nolint
                  function(j) {
                    mean(istd_sum[[a]][
                      grepl(
                        j,
                        colData(dnorm)[[metadata(dnorm)[["Batch column name"]]]] # nolint
                      )
                    ])
                  }
                )
              )
            }
          )
        ), names(istd_sum))
      }
      if ("Batch column name" %in% names(metadata(dnorm)) == FALSE) { # nolint
        istd_avg <- unlist(lapply(names(istd_sum), function(x) mean(x)))
      }
      ## Normalize each compound to iSTD average
      SummarizedExperiment::assay(
        dnorm, "norm", withDimnames = FALSE
      ) <- as.matrix(
        dplyr::bind_rows(
          lapply(
            seq.int(1, nrow(dnorm), 1),
            function(x) {
              # Select row
              d1 <- SummarizedExperiment::assay(dnorm, "imputed")[x, ]
              # Calculate normalized peak heights
              ## toggle between ionization modes
              d1 <- (
                # raw peak height
                d1 /
                  # internal standard sum for mode
                  istd_sum[[rowData(dnorm)[["Mode"]][[x]]]] # nolint
              ) *
                # internal standard average sum for mode
                istd_avg[[rowData(dnorm)[["Mode"]][[x]]]]
              return(d1) # nolint
            }
          )
        )
      )
      # Add raw/imputed/norm TIC columns to column metadata
      colData(dnorm) <- cbind( # nolint
        colData(dnorm), # nolint
        dplyr::bind_cols(
          lapply(
            metadata(dnorm)[["Ionization mode"]], # nolint
            function(i) {
              setNames(as.data.frame(lapply(
                names(assays(dnorm)), # nolint
                function(j) {
                  colSums(assay(dnorm, j)[ # nolint
                    grepl(i, rowData(dnorm)[["Mode"]]), # nolint
                  ])
                }
              )), paste("TIC", i, names(assays(dnorm)), sep = ".")) # nolint
            }
          )
        )
      )
    }
    metadata(dnorm)[["Normalization method"]] <- "iSTD" # nolint
  }
  print("Normalization successful!")
  return(dnorm)
}

#' Normalization QC
#'
#' Scatter plot visualization to evaluate normalization performance.
#'
#' @param df input data from list data object.
#' @param var_x X-axis variable (usually sample ID).
#' @param var_g Grouping variable.
#' @return A scatter plot visualizing overall sample intensities.
#' @examples
#'
#' # ptic <- msi_plot_tic(
#' #   df = ld[["meta"]],
#' #   var_x = "sampleID",
#' #   var_g = "Group"
#' # )
#'
#' @import ggplot2
#' @export
ms_plot_tic <- function(
  df,
  var_x,
  var_g = "Group"
) {
  ## TIC plot
  ggplot2::ggplot(
    df
  ) +
    ggplot2::geom_point(
      ggplot2::aes(
        x = .data[[var_x]], # nolint
        y = .data[["TIC.prenorm"]],
        color = as.factor(.data[[var_g]])
      ),
      shape = 16,
      size = 1,
      alpha = 0.5
    ) +
    ggplot2::geom_smooth(
      color = "firebrick1",
      alpha = 0.5,
      ggplot2::aes(x = .data[[var_x]], y = .data[["TIC.prenorm"]])
    ) +
    ggplot2::labs(y = "TIC",
      x = "Sample ID"
    ) +
    ggplot2::scale_color_manual(values = col_univ()) + # nolint
    ggplot2::geom_point(
      ggplot2::aes(
        x = .data[[var_x]],
        y = df[["TIC.postnorm"]],
        color = as.factor(.data[[var_g]])
      ),
      shape = 16,
      size = 1,
      alpha = 0.8
    ) +
    ggplot2::geom_smooth(
      color = "dodgerblue1",
      alpha = 0.8,
      ggplot2::aes(x = .data[[var_x]], y = df[["TIC.postnorm"]])
    ) +
    ggplot2::labs(y = "TIC",
      x = "Sample ID"
    ) +
    ms_theme() # nolint
}
