#' Volcano Plot
#'
#' Generates a volcano plot from a statistical results object for
#' a chosen comparison.
#'
#' @param d_stat Univariate results list generated by ms_stat_anova().
#' @param comp_name Comparison name, provided as a character string.
#' @param diff_col Column name containing effect size.
#' @param p_col Column name containing adjusted p-values.
#' @param p_cut Numeric value for p-value cutoff to indicate significance.
#' @param f_cut Fold change cutoff indicating high effect size.
#' @param f_lim Numeric value for fold change limits on the x-axis.
#' @param y_limit Upper-bound -log10 p-value to display on the y-axis.
#' @param x_title X-axis legend title, provided as a character string.
#' @return A volcano plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_volcano(
#' #   d_stat = d[["stats"]],
#' #   comp_name = "KO vs. Control",
#' #   diff_col = "Log2FC",
#' #   p_col = "p adj",
#' #   p_cut = 0.05,
#' #   f_cut = 0.25,
#' #   f_lim = 6,
#' #   y_limit = 10,
#' #   x_title = "x-axis title"
#' # )
#'
#' @export
ms_plot_volcano <- function(
  d_stat,
  comp_name,
  diff_col = "Log2FC",
  p_col = "p.value",
  p_cut = 0.05,
  f_cut = 0.5,
  f_lim = 5,
  y_limit = 5,
  x_title
) {
  # Subset Input data
  ld <- d_stat
  ld <- ld[ld[["Comparison"]] == comp_name, ]
  # Plot function
  v <- EnhancedVolcano::EnhancedVolcano(
    ld,
    lab = ld[["Name"]],
    title = ggplot2::element_blank(),
    subtitle = ggplot2::element_blank(),
    caption = ggplot2::element_blank(),
    x = diff_col,
    y = p_col,
    pCutoff = p_cut,
    FCcutoff = f_cut,
    cutoffLineType = "twodash",
    legendLabels = c("NS", "Fold Change",
                     "p-value", "FC+P"),
    legendLabSize = 12,
    labFace = "bold",
    col = ggsci::pal_npg("nrc")(10)[c(4, 3, 5, 8)],
    colAlpha = 0.7,
    legendIconSize = 4,
    pointSize = 2,
    border = "full",
    borderWidth = 1.5,
    legendPosition = "'right'",
    labSize = 3,
    drawConnectors = TRUE,
    max.overlaps = 10,
    typeConnectors = "open",
    min.segment.length = ggplot2::unit(
      1,
      "mm"
    )
  ) +
    ms_theme() + # nolint
    ggplot2::labs(color = "Key") +
    ggplot2::labs(
      color = "Key",
      x = x_title,
      y = paste("-log10 P-value")
    ) +
    ggplot2::theme(plot.margin = ggplot2::unit(c(.2, .2, .2, .2), "cm")) +
    ggplot2::coord_cartesian(xlim = c(-f_lim, f_lim),
                             ylim = c(0, y_limit)) +
    ggplot2::scale_x_continuous(breaks = seq(-f_lim, f_lim, (f_lim / 4)))
  return(v)
}

#' Heatmap 1
#'
#' Generates a heatmap from a statistical results object for
#' a vector of comparisons.
#'
#' @param d_stat Univariate results list generated by ms_stat_anova().
#' @param d_ref Reference annotation list generated by ms_input(),
#' which is only used if plotting a heatmap annotation.
#' @param c_list Comparison list, provided as a vector.
#' @param diff_col Column name containing effect size.
#' @param comp_col Fold change comparison column.
#' @param p_col Column name containing adjusted p-values.
#' @param an1 Variable names used for annotating the heatmap.
#' @param hm_w Heatmap width.
#' @param hm_h Heatmap height.
#' @param fs_r Row fontsize.
#' @param fs_c Column fontsize.
#' @param cl_c Logical indicating if the columns should be clustered.
#' @param cl_r Logical indicating if the rows should be clustered.
#' @param cn Show column names.
#' @param rn Show row names.
#' @param filtp Filter heatmap based on a p-value cutoff of 0.05.
#' @param scm1 Heatmap color scheme to use.
#' @param col_fun Color ramp function
#' (either by 4 quantiles [1] or by upper and lower quantiles[2]).
#' @return A heatmap for the selected comparisons.
#' @examples
#'
#' # ms_plot_heat(
#' #   d_stat = d[["stats"]],
#' #   c_list = c("KO vs. Control")
#' # )
#'
#' @export
ms_plot_heat <- function(
  d_stat,
  d_ref = NULL,
  c_list,
  comp_col = "Comparison.fc",
  diff_col = "Log2FC",
  p_col = "p.value",
  an1 = NULL,
  hm_w = 36,
  hm_h = 10,
  fs_r = 8,
  fs_c = 8,
  cl_c = TRUE,
  cl_r = TRUE,
  cn = TRUE,
  rn = TRUE,
  filtp = FALSE,
  scm1 = col_grad(scm = 3), # nolint
  col_fun = 1
) {
  # Load and subset data
  hd1 <- d_stat
  href <- d_ref
  hm_list <- c_list
  an2 <- an1
  hm_in <- hd1[hd1[[comp_col]] %in% hm_list, ]
  # Format and prepare FC and P matrices
  hd <- reshape2::dcast(
    hm_in[, c(diff_col, comp_col, "Name")],
    Comparison.fc ~ Name,
    value.var = diff_col
  )
  hp <- reshape2::dcast(
    hm_in[, c(p_col, comp_col, "Name")],
    Comparison.fc ~ Name,
    value.var = p_col
  )
  hd_in <- as.matrix(hd[, 2:ncol(hd)])
  rownames(hd_in) <- hd[[1]]
  hd_in[is.na(hd_in)] <- max(hd_in[!is.na(hd_in)])
  hp_in <- as.matrix(hp[, 2:ncol(hp)])
  rownames(hp_in) <- hp[[1]]
  hp_in[is.na(hp_in)] <- min(hp_in[!is.na(hp_in)])
  # Figure annotations, colors, and scales
  qs <- quantile(
    hd_in,
    probs = c(
      0.05,
      0.95
    ),
    na.rm = TRUE
  )
  if(col_fun == 1) { # nolint
    fun_hm_col <- circlize::colorRamp2(
      c(
        qs[[1]],
        (qs[[1]]) / 2,
        (qs[[2]]) / 2,
        qs[[2]]
      ),
      colors = c(
        scm1
      )
    )
  }
  if(col_fun == 2) { # nolint
    fun_hm_col <- circlize::colorRamp2(
      c(
        qs[[1]],
        0,
        qs[[2]]
      ),
      colors = c(
        scm1
      )
    )
  }
  if(is.null(an2) == FALSE) { # nolint
    fun_hm_bar <- list(
      "Class" = setNames(
        col_univ()[1:length(unique(href[[an2[[1]]]]))], # nolint
        as.character(unique(href[[an2[[1]]]]))
      ),
      "Saturation" = setNames(
        col_univ()[1:length(unique(href[[an2[[2]]]]))], # nolint
        as.character(unique(unique(href[[an2[[2]]]])))
      )
    )
    ### Annotations
    hm_anno_list <- list(
      "column1" = ComplexHeatmap::HeatmapAnnotation(
        `Class` = (href[[an2[[1]]]]),
        `Saturation` = (href[[an2[[2]]]]),
        col = fun_hm_bar,
        show_annotation_name = FALSE
      )
    )
    if(filtp == TRUE) { # nolint
      # Create Plot
      h_out <- ComplexHeatmap::Heatmap(
        hd_in,
        # p-value filter
        layer_fun = function(j, i, x, y, w, h, fill) {
          # map positions of fold change matrix cells onto pvalue heatmap
          p_pos <- ComplexHeatmap::pindex(hp_in, i, j)
          # filter non-significant p values to fill in blanks
          p_blank <- p_pos > 0.05
          # create matrix for subsetting the heatmap
          # to display only significant cells
          p <- ComplexHeatmap::restore_matrix(j, i, x, y) # nolint
          # mask non-significant genes
          grid::grid.rect(
            x[p_blank],
            y[p_blank],
            w,
            h,
            gp = grid::gpar(col = "white")
          )
        },
        col = fun_hm_col,
        top_annotation = hm_anno_list[[1]],
        name = "Log2-Fold Change",
        show_column_names = cn,
        show_row_names = rn,
        heatmap_width = ggplot2::unit(hm_w, "cm"),
        heatmap_height = ggplot2::unit(hm_h, "cm"),
        row_names_side = "left",
        row_names_gp = grid::gpar(fontsize = fs_r),
        column_names_gp = grid::gpar(fontsize = fs_c),
        cluster_columns = cl_c,
        cluster_rows = cl_r
      )
    }
    if(filtp == FALSE) { # nolint
      # Create Plot
      h_out <- ComplexHeatmap::Heatmap(
        hd_in,
        col = fun_hm_col,
        top_annotation = hm_anno_list[[1]],
        name = "Log2-Fold Change",
        show_column_names = cn,
        show_row_names = rn,
        heatmap_width = ggplot2::unit(hm_w, "cm"),
        heatmap_height = ggplot2::unit(hm_h, "cm"),
        row_names_side = "left",
        row_names_gp = grid::gpar(fontsize = fs_r),
        column_names_gp = grid::gpar(fontsize = fs_c),
        cluster_columns = cl_c,
        cluster_rows = cl_r
      )
    }
  }
  if(is.null(an2) == TRUE) { # nolint
    if(filtp == TRUE) { # nolint
      # Create Plot
      h_out <- ComplexHeatmap::Heatmap(
        hd_in,
        # p-value filter
        layer_fun = function(j, i, x, y, w, h, fill) {
          # map positions of fold change matrix cells onto pvalue heatmap
          p_pos <- ComplexHeatmap::pindex(hp_in, i, j)
          # filter non-significant p values to fill in blanks
          p_blank <- p_pos > 0.05
          # create matrix for subsetting the heatmap
          # to display only significant cells
          p <- ComplexHeatmap::restore_matrix(j, i, x, y) # nolint
          # mask non-significant genes
          grid::grid.rect(
            x[p_blank],
            y[p_blank],
            w,
            h,
            gp = grid::gpar(col = "white")
          )
        },
        col = fun_hm_col,
        name = "Log2-Fold Change",
        show_column_names = cn,
        show_row_names = rn,
        heatmap_width = ggplot2::unit(hm_w, "cm"),
        heatmap_height = ggplot2::unit(hm_h, "cm"),
        row_names_side = "left",
        row_names_gp = grid::gpar(fontsize = fs_r),
        column_names_gp = grid::gpar(fontsize = fs_c),
        cluster_columns = cl_c,
        cluster_rows = cl_r
      )
    }
    if(filtp == FALSE) { # nolint
      # Create Plot
      h_out <- ComplexHeatmap::Heatmap(
        hd_in,
        col = fun_hm_col,
        name = "Log2-Fold Change",
        show_column_names = cn,
        show_row_names = rn,
        heatmap_width = ggplot2::unit(hm_w, "cm"),
        heatmap_height = ggplot2::unit(hm_h, "cm"),
        row_names_side = "left",
        row_names_gp = grid::gpar(fontsize = fs_r),
        column_names_gp = grid::gpar(fontsize = fs_c),
        cluster_columns = cl_c,
        cluster_rows = cl_r
      )
    }
  }
  return(h_out)
}

#' Scatter Plot
#'
#' Generates a scatter plot from a statistical results object for
#' a chosen comparison.
#'
#' @param df1 Input data frame.
#' @param type1 Scatter plot type (either "std" or "oxview").
#' If type is "oxview," a variable indicating either "Oxidized"
#' or "Unoxidized" lipids must be present in the input data frame.
#' @param xvar X-axis variable.
#' @param yvar Y-axis variable.
#' @param clvar Group variable.
#' @param oxvar (optional) If type is "oxview," the variable name
#' distinguishing oxidized from unoxidized lipids.
#' @param bns (optional) Bin number for scatter plot types using
#' stat_density_2d().
#' @return A scatter plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_scatter(
#' #   df1 = dox,
#' #   type1 = "oxview",
#' #   xvar = "rt",
#' #   yvar = "mz",
#' #   clvar = "class"
#' # )
#'
#' @export
ms_plot_scatter <- function(
  df1,
  type1,
  xvar,
  yvar,
  clvar,
  oxvar = "ox",
  bns = 50
) {
  d <- df1
  if(type1 == "oxview") { # nolint
    ggplot2::ggplot(
      d,
      ggplot2::aes(
        x = .data[[xvar]], # nolint
        y = .data[[yvar]],
        color = .data[[clvar]],
        label = .data[[clvar]]
      )
    ) +
      ggplot2::scale_fill_manual(
        name = "Type",
        values = rep(
          col_univ()[[2]], # nolint
          length(unique(d[d[[oxvar]] == "Unoxidized", ][[clvar]]))
        )
      ) +
      ggplot2::stat_density_2d(
        data = d[d[[oxvar]] == "Unoxidized", ],
        ggplot2::aes(
          fill = d[d[[oxvar]] == "Unoxidized", ][[clvar]]
        ),
        geom = "polygon",
        alpha = 0.1,
        linewidth = 0.01,
        bins = bns,
        contour = TRUE,
        show.legend = FALSE
      ) +
      ggnewscale::new_scale_fill() +
      ggplot2::scale_fill_manual(
        name = "Type",
        values = rep(
          col_univ()[[1]],
          length(unique(d[d[[oxvar]] == "Oxidized", ][[clvar]]))
        )
      ) +
      ggplot2::stat_density_2d(
        data = d[d[[oxvar]] == "Oxidized", ],
        ggplot2::aes(
          fill = d[d[[oxvar]] == "Oxidized", ][[clvar]]
        ),
        geom = "polygon",
        alpha = 0.4,
        linewidth = 0.01,
        bins = bns,
        contour = TRUE,
        show.legend = FALSE
      ) +
      ggnewscale::new_scale_fill() +
      ggplot2::scale_color_manual(
        name = "Class",
        values = col_univ()
      ) +
      ggplot2::geom_point(
        shape = 16,
        size = 1,
        alpha = 0.6
      ) +
      ggrepel::geom_text_repel(
        data = setNames(
          aggregate(
            d[, c(yvar, xvar)],
            list(d[[clvar]]),
            FUN = median
          ),
          c(clvar, yvar, xvar
          )
        ),
        size = 3,
        bg.color = "grey0",
        color = "white",
        bg.r = 0.05
      ) +
      # Add Theme
      ms_theme1() + # nolint
      ggplot2::labs(
        y = "m/z",
        x = "RT (min.)",
        color = "Class"
      ) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(
          c(
            0.1,
            0.1,
            0.1,
            0.1
          ),
          "cm"
        )
      )
  }
}

#' Violin/Box Plot
#'
#' Generates a violin plot from an input data frame.
#'
#' @param exp1 SummarizedExperiment object.
#' @param asy Assay to use for plotting.
#' @param ptype Plot type (either "vio" or "box")
#' @param var_x X-axis variable name from colData.
#' @param var_c Variable containing compound names.
#' @param var_cl Group variable name from colData.
#' @param var_sum Variable name for summarizing
#' compound information (optional).
#' @param var_id Sample ID variable name; only
#' required if var_sum is provided.
#' @param comp Compound name to plot.
#' @param plab Y-axis label.
#' @param title1 Plot title.
#' @param show_jitter Show individual data points on the plot?
#' @return A violin plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_vio(
#' #   exp1 = data2,
#' #   comp = "Compound1"
#' # )
#'
#' @export
ms_plot_vio <- function(
  exp1,
  asy = "norm",
  ptype = "vio",
  var_x = "Region",
  var_c = "Label",
  var_cl = "Group",
  var_sum = NULL,
  var_id = NULL,
  comp,
  plab = "Relative Abundance",
  title1 = NULL,
  show_jitter = FALSE
) {
  # Load data and format as data frame
  d1 <- exp1
  if (is.null(var_sum)) {
    v1 <- as.vector(
      t(assay(d1[rowData(d1)[[var_c]] == comp, ], asy)) # nolint
    )
    df1 <- data.frame(
      "x" = factor(
        colData(d1)[[var_x]], # nolint
        levels = gtools::mixedsort(
          unique(colData(d1)[[var_x]])
        )
      ),
      "y" = v1,
      "grp" = factor(
        colData(d1)[[var_cl]],
        levels = gtools::mixedsort(
          unique(colData(d1)[[var_cl]])
        )
      )
    )
    # Plot
    pv <- ggplot2::ggplot(
      data = df1,
      ggplot2::aes(
        x = .data[["x"]], # nolint
        y = .data[["y"]],
        fill = .data[["grp"]]
      )
    ) +
      ggplot2::scale_fill_manual(name = "Group", values = col_univ()) + # nolint
      # Add Theme
      ms_theme() + # nolint
      ggplot2::labs(x = "", y = plab, title = title1) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(c(0.1, 0.1, 0.1, 0.1), "cm")
      )
    if (ptype == "vio") {
      pv <- pv +
        ggplot2::geom_violin(trim = TRUE)
    }
    if (ptype == "box") {
      pv <- pv +
        ggplot2::geom_boxplot()
    }
    if (show_jitter == TRUE) {
      pv <- pv +
        ggplot2::geom_jitter(
          ggplot2::aes(
            alpha = 0.2
          ),
          shape = 16,
          size = 1,
          position = ggplot2::position_jitter(
            width = 0.1
          ),
          show.legend = FALSE
        )
    }
  }
  if (!is.null(var_sum)) {
    df1 <- dplyr::bind_cols(
      data.frame("GroupID" = unique(rowData(d1)[[var_sum]])), # nolint
      dplyr::bind_cols(
        lapply(
          seq.int(1, ncol(d1), 1),
          function(i) {
            setNames(as.data.frame(aggregate(
              as.vector(assay(d1, asy)[, i]), # nolint
              list(rowData(d1)[[var_sum]]), # nolint
              function(j) mean(j)
            )[[2]]), colData(d1)[[var_id]][[i]]) # nolint
          }
        )
      )
    )
    df1 <- setNames(reshape2::melt(
      df1, id.vars = "GroupID"
    ), c("GroupID", var_id, "value"))
    df2 <- as.data.frame(colData(d1)[, c(var_id, var_cl, var_x)]) # nolint
    df2[[var_id]] <- factor(df2[[var_id]], levels = levels(df1[[var_id]]))
    df1 <- dplyr::left_join(df1, df2, by = var_id)
    # Plot
    pv <- ggplot2::ggplot(
      data = df1,
      ggplot2::aes(
        x = .data[["GroupID"]], # nolint
        y = .data[["value"]],
        fill = .data[[var_cl]]
      )
    ) +
      ggplot2::scale_fill_manual(name = var_cl, values = col_univ()) + # nolint
      # Add violin plot and dotplot
      # Add Theme
      ms_theme() + # nolint
      ggplot2::labs(x = "", y = plab, title = title1) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(c(0.1, 0.1, 0.1, 0.1), "cm")
      )
    if (ptype == "vio") {
      pv <- pv +
        ggplot2::geom_violin(trim = TRUE)
    }
    if (ptype == "box") {
      pv <- pv +
        ggplot2::geom_boxplot()
    }
  }
  return(pv) # nolint
}

#' Bar Plot
#'
#' Generates a bar plot with error bars from an input data frame.
#'
#' @param ptype Bar plot type (either "stacked" or "std").
#' @param df1 Input data frame.
#' @param df2 Data frame containing group standard deviations (for error bars).
#' @param xvar X-axis variable.
#' @param yvar Y-axis variable.
#' @param clvar Group variable.
#' @param plab Plot y-axis label.
#' @param labvar Additional variable for plotting proportions (optional).
#' @return A bar plot for the chosen treatment comparisons.
#' @examples
#'
#' # ms_plot_bar(
#' #   df1 = dox,
#' #   xvar = "rt",
#' #   yvar = "mz"
#' # )
#'
#' @export
ms_plot_bar <- function(
  ptype = "stacked",
  df1,
  df2 = NULL,
  xvar = "Assay",
  yvar = "Count",
  clvar = "Class",
  labvar = NULL,
  plab = "Proportion"
) {
  # Load data
  d1 <- df1
  #---- Stacked bar ----
  if (ptype == "stacked") {
    pv <- ggplot2::ggplot(
      data = d1,
      ggplot2::aes(
        x = .data[[xvar]], # nolint
        y = .data[[yvar]],
        fill = .data[[clvar]]
      )
    ) +
      ggplot2::scale_fill_manual(
        name = clvar,
        values = col_univ() # nolint
      ) +
      # Add barplot
      ggplot2::geom_bar(
        ggplot2::aes(
          fill = .data[[clvar]]
        ),
        stat = "identity",
        position = "fill",
        width = 0.6,
        color = "grey25"
      ) +
      shadowtext::geom_shadowtext(
        ggplot2::aes(label = .data[[labvar]]),
        position = ggplot2::position_fill(
          vjust = 0.5
        ),
        size = 3,
        color = "white",
        bg.color = "grey25",
        bg.r = 0.1,
        fontface = "bold"
      ) +
      # Add Theme
      ms_theme() + # nolint
      ggplot2::labs(
        y = plab,
        x = ""
      ) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(
          c(
            0.5,
            0.5,
            0.5,
            0.5
          ),
          "cm"
        ),
        axis.text.y = ggplot2::element_text(
          face = "bold",
          size = 12
        ),
        axis.title.y = ggplot2::element_text(
          face = "bold",
          size = 12
        )
      )
  }
  #---- Standard bar ----
  if (ptype == "std") {
    pv <- ggplot2::ggplot(
      data = d1,
      ggplot2::aes(
        x = .data[[xvar]], # nolint
        y = .data[[yvar]],
        fill = .data[[clvar]]
      )
    ) +
      ggplot2::scale_fill_manual(
        name = clvar,
        values = col_univ() # nolint
      ) +
      # Add barplot
      ggplot2::geom_bar(
        stat = "summary",
        fun = mean,
        position = "dodge",
        width = 0.6,
        color = "grey25"
      ) +
      ggplot2::geom_errorbar(
        data = df2,
        ggplot2::aes(
          x = .data[[xvar]],
          y = .data[["mean"]],
          ymin = .data[["mean"]] - .data[["sd"]],
          ymax = .data[["mean"]] + .data[["sd"]]
        ),
        position = "dodge",
        width = 0.6,
        color = "grey25"
      ) +
      # Add Theme
      ms_theme() + # nolint
      ggplot2::labs(
        title = yvar,
        y = plab,
        x = ""
      ) +
      ggplot2::theme(
        plot.margin = ggplot2::unit(
          c(
            0.5,
            0.5,
            0.5,
            0.5
          ),
          "cm"
        ),
        axis.text.y = ggplot2::element_text(
          face = "bold",
          size = 12
        ),
        axis.title.y = ggplot2::element_text(
          face = "bold",
          size = 12
        )
      )
  }
  return(pv) # nolint
}

#' General Heatmap
#'
#' Generates a heatmap from a SummarizedExperiment.
#'
#' @param exp1 A SummarizedExperiment object.
#' @param stat_data Generate heatmap based on statistical results instead
#' of intensity/abundance values from a summarizedexperiment. Results
#' tables should be formatted according to outputs from ms_stat_uni.
#' @param deg_sig Should only compounds/features with statistically significant
#' differences in intensity/abundance be plotted?
#' @param l_cstm (optional) Filter data based on custom compound list.
#' @param asy Assay to use (ex. "norm" or "scaled").
#' @param asy_type Assay type (either "norm" or "scaled"). If "scaled",
#' the input data undergo no additional scaling.
#' @param cl_var Grouping variable name.
#' @param feat_var Variable from rowData containing compound names.
#' @param h_w Numeric value for heatmap width (passed to ComplexHeatmap).
#' @param h_h Numeric value for heatmap height (passed to ComplexHeatmap).
#' @param fs_c Numeric value for column fontsize (passed to ComplexHeatmap).
#' @param fs_r Numeric value for row fontsize (passed to ComplexHeatmap).
#' @param cl_c Cluster columns?
#' @param cl_r Cluster rows?
#' @param rc Show column names?
#' @param rn Show row names?
#' @param rot_c Rotation of column names.
#' @param col1 Gradient color scheme to use.
#' @param transp Transpose heatmap input matrix (FALSE by default).
#' @param legend1 Figure legend name.
#' @return A ComplexHeatmap object.
#' @examples
#'
#' # ms_plot_hm(exp1 = data1)
#'
#' @export
ms_plot_hm <- function(
  exp1 = NULL,
  stat_data = NULL,
  deg_sig = FALSE,
  l_cstm = NULL,
  asy = "scaled",
  asy_type = "scaled",
  cl_var = "Group",
  feat_var = "Label",
  h_w = 40,
  h_h = 20,
  fs_c = 6,
  fs_r = 8,
  cl_c = FALSE,
  cl_r = FALSE,
  rot_c = 45,
  rc = TRUE,
  rn = TRUE,
  col1 = col_grad(scm = 5), # nolint
  transp = FALSE,
  legend1 = "Abundance"
) {
  #---- Select Compounds to Plot ----
  # If stats data are not provided,
  # return either all compounds or a custom list
  if (is.null(stat_data)) {
    # load sumexp
    d <- exp1
    # if custom list is not provided
    if (is.null(l_cstm)) {
      cl_mark <- rowData(d)[[feat_var]] # nolint
    }
    if (!is.null(l_cstm)) {
      cl_mark <- rowData(d)[rowData(d)[[feat_var]] %in% l_cstm, ] # nolint
    }
    # Subset data and format as matrix
    h <- setNames(
      data.frame(
        colData(d)[[cl_var]], # nolint
        as.data.frame(
          t(assay(d, asy)[rowData(d)[[feat_var]] %in% cl_mark, ]) # nolint
        )
      ),
      c("Group", cl_mark)
    )
    h[[1]] <- factor(
      as.character(h[[1]]),
      levels = gtools::mixedsort(unique(as.character(h[[1]])))
    )
  }
  if (!is.null(stat_data)) {
    h <- stat_data
  }
  #---- Format input data matrix ----
  # Standard input
  if (is.null(stat_data)) {
    h_in <- as.matrix(
      magrittr::set_rownames(
        setNames(
          as.data.frame(
            lapply(
              h[, 2:ncol(
                h
              )],
              function(x) {
                dplyr::select(
                  aggregate(
                    x,
                    list(
                      h[, 1]
                    ),
                    FUN = mean
                  ),
                  c(2)
                )
              }
            )
          ),
          names(h[, 2:ncol(h)])
        ),
        levels(h[, 1])
      )
    )
  }
  # Stats input
  if (!is.null(stat_data)) {
    # Format stats results as matrix
    # and include only significant compounds
    if (deg_sig == TRUE) {
      h_in <- h[h[["p.value"]] < 0.05, ]
    }
    if (deg_sig == FALSE) {
      h_in <- h
    }
    # reassign factor levels
    h_in[["Group"]] <- factor(
      as.character(h_in[["Comparison"]]),
      levels = gtools::mixedsort(
        unique(as.character(h_in[["Comparison"]]))
      )
    )
    # Create matrix
    h_in <- reshape2::dcast(
      h_in[, c("Group", "Name", "Log2FC")],
      Group ~ Name,
      value.var = "Log2FC"
    )
    h_in <- as.matrix(
      magrittr::set_rownames(
        setNames(
          h_in[, 2:ncol(h_in)],
          names(h_in[, 2:ncol(h_in)])
        ),
        levels(h_in[[1]])
      )
    )
  }
  qs <- quantile(
    h_in,
    probs = c(
      0.05,
      0.95
    ),
    na.rm = TRUE
  )
  if (is.null(stat_data)) {
    h_in <- as.matrix(
      as.data.frame(h_in)[, unlist(
        lapply(
          seq.int(1, ncol(as.data.frame(h_in)), 1),
          function(x) {
            !anyNA(as.data.frame(h_in)[x])
          }
        )
      )
      ]
    )
  }
  if (transp == TRUE) {
    h_in <- t(h_in)
  }
  if (qs[[1]] < 0) {
    fun_hm_col <- circlize::colorRamp2(
      c(
        qs[[1]],
        0,
        qs[[2]]
      ),
      colors = col1
    )
  }
  if (qs[[1]] > 0) {
    fun_hm_col <- circlize::colorRamp2(
      c(
        qs[[1]],
        round(mean(c(qs[[1]], qs[[2]])), digits = 0),
        qs[[2]]
      ),
      colors = col_grad(scm = 4) # nolint
    )
  }
  # Create Plot
  h_out <- ComplexHeatmap::Heatmap(
    h_in,
    col = fun_hm_col,
    name = legend1,
    show_column_names = rc,
    show_row_names = rn,
    heatmap_width = ggplot2::unit(h_w, "cm"),
    heatmap_height = ggplot2::unit(h_h, "cm"),
    column_names_rot = rot_c,
    column_names_gp = grid::gpar(fontsize = fs_c),
    row_names_side = "left",
    row_names_gp = grid::gpar(fontsize = fs_r),
    cluster_columns = cl_c,
    cluster_rows = cl_r
  )
  return(h_out)
}

#' Plot ChemRICH Results
#'
#' Plots ChemRICH results for selected comparison as a dot plot.
#'
#' @param dfcr An individual comparison from a ChemRICH results data frame.
#' @return A dot plot displaying ChemRICH results,
#' including cluster size, increased/decreased proportion,
#' and statistical significance.
#' @examples
#' # ms_plot_crich(
#' #   dfcr = chemrichdf
#' # )
#'
#' @export
ms_plot_crich <- function(
  dfcr
) {
  df <- dfcr
  # Main Plot
  cr_plot <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = df[[4]], # nolint
      y = -log10(FDR), # nolint
      fill = Ratio # nolint
    )
  ) +
    ## Connect lines to significantly altered clusters
    ggplot2::geom_linerange(
      data = df[df[["FDR"]] < 0.05, ],
      ggplot2::aes(
        x = df[df[["FDR"]] < 0.05, 4],
        ymax = -log10(df[df[["FDR"]] < 0.05, "FDR"]),
        ymin = 0
      ),
      color = "black"
    ) +
    ## Plot points
    ggplot2::geom_point(
      shape = 21,
      col = "black",
      ggplot2::aes(
        size = .data[["n"]] # nolint
      ),
      alpha = ifelse(
        df[["FDR"]] < 0.05,
        1,
        0.5
      )
    ) +
    ## Significance line
    ggplot2::geom_hline(
      yintercept = 1.3,
      linetype = "dashed",
      color = col_univ()[[1]] # nolint
    ) +
    ## Theme
    ms_theme() + # nolint
    ggplot2::theme(plot.margin = grid::unit(
      c(1, 4, 1, 4),
      "cm"
    )) +
    ## Axis labels
    ggplot2::xlab("Class") +
    ggplot2::ylab("-log10(adjusted p-value)") +
    ## Gradient and size scaling
    ggplot2::scale_fill_gradientn(
      name = "Increased Ratio",
      colors = c(
        "midnightblue",
        "royalblue2",
        "white",
        "goldenrod1",
        "firebrick3"
      ),
      breaks = c(
        0, .25, .5, .75, 1
      ),
      labels = c(
        "100% Decreased",
        "25% Increased:75% Decreased",
        "50% Increased:50% Decreased",
        "75% Increased:25% Decreased",
        "100% Increased"
      )
    ) +
    ggplot2::scale_size_area(
      name = "Cluster Size",
      max_size = 16
    )
  return(cr_plot) # nolint
}
